"""The typed surface of ``hypercast._native``, the PyO3 extension (``tests/test_typing.py``
holds the loaded module to this file). ``hypercast`` re-exports all of it directly, so this
is what a type checker sees behind every door: its own ``Success[...] | Fault``, which is
what lets a ``match`` over the two cases be checked for exhaustiveness with
``typing.assert_never``.
"""

import datetime
import decimal
import uuid
from typing import Any, ClassVar, Final, Generic, TypeVar, final

from . import CastFailure, DateOrder, ExcelEpoch, UnixPrecision

_T_co = TypeVar("_T_co", covariant=True)

@final
class Success(Generic[_T_co]):
    __match_args__: Final = ("value",)
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, value: _T_co) -> Success[_T_co]: ...
    @property
    def value(self) -> _T_co: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Fault:
    __match_args__: Final = ("reason", "offset", "length")
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, reason: CastFailure, offset: int, length: int) -> Fault: ...
    @property
    def reason(self) -> CastFailure: ...
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class NumFormat:
    GROUPING: ClassVar[int]
    PARENTHESES: ClassVar[int]
    EXPONENT: ClassVar[int]
    RADIX_PREFIXES: ClassVar[int]
    PERCENT: ClassVar[int]
    CURRENCY: ClassVar[int]
    ALL: ClassVar[int]
    SEPARATOR_DETECT: ClassVar[int]
    INVARIANT: ClassVar[NumFormat]
    DETECT: ClassVar[NumFormat]
    def __new__(
        cls, decimal_sep: str, group_sep: str, flags: int, currency: str = ""
    ) -> NumFormat: ...
    @property
    def decimal_sep(self) -> str: ...
    @property
    def group_sep(self) -> str: ...
    @property
    def flags(self) -> int: ...
    @property
    def currency(self) -> str: ...
    @property
    def packed(self) -> bytes:
        """The 32 bytes this format crosses a C ABI as, for a library with one of its own."""
    @staticmethod
    def from_localeconv(conv: dict[str, Any] | None = None) -> NumFormat: ...

def cast_bool(text: str | bytes) -> Success[bool] | Fault: ...
def cast_char(text: str | bytes) -> Success[str] | Fault: ...
def cast_i8(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_i16(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_i32(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_i64(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_u8(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_u16(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_u32(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_u64(text: str | bytes, fmt: NumFormat) -> Success[int] | Fault: ...
def cast_f32(text: str | bytes, fmt: NumFormat) -> Success[float] | Fault: ...
def cast_f64(text: str | bytes, fmt: NumFormat) -> Success[float] | Fault: ...
def cast_decimal(text: str | bytes, fmt: NumFormat) -> Success[decimal.Decimal] | Fault: ...
def cast_uuid(text: str | bytes) -> Success[uuid.UUID] | Fault: ...
def cast_timestamp(text: str | bytes) -> Success[datetime.datetime] | Fault: ...
def cast_unix(
    text: str | bytes, precision: UnixPrecision
) -> Success[datetime.datetime] | Fault: ...
def cast_excel_serial(
    text: str | bytes, epoch: ExcelEpoch
) -> Success[datetime.datetime] | Fault: ...
def cast_date(
    text: str | bytes, order: DateOrder | None = None
) -> Success[datetime.date] | Fault: ...
def cast_datetime(text: str | bytes, order: DateOrder) -> Success[datetime.datetime] | Fault: ...
def cast_time(text: str | bytes) -> Success[datetime.time] | Fault: ...
def cast_duration(text: str | bytes) -> Success[datetime.timedelta] | Fault: ...
def cast_decimal_from_float(value: float) -> Success[decimal.Decimal] | Fault: ...
def cast_excel_serial_from_float(
    value: float, epoch: ExcelEpoch
) -> Success[datetime.datetime] | Fault: ...
def cast_excel_time(value: float) -> Success[datetime.time] | Fault: ...
def cast_excel_duration(value: float) -> Success[datetime.timedelta] | Fault: ...
def native_version() -> str: ...
def _bind(cast_failure: type[CastFailure]) -> None: ...
